### ISSUE TITLE
Quickstart for bitthunder and the pi

### ISSUE THREAD

**Issue by ririw** [jameswalmsley/bitthunder#41]
Hey, I've just worked out how to run bitthunder on the pi, but the existing docs are a little out of date.

I've documented how I did it [here](http://blog.richardweiss.org/2015/06/27/raspberry-pi-bitthunder.html).

If you want I can go and edit the bitthunder docs to update them, or you can link straight to that blog post. 

p.s. thanks for making bitthunder.

**Comment by jameswalmsley** [comment]
Hi,
Really grateful for your efforts on this. I'll make a link to your blog for now, because I think you make it very clear actually.

If you also connect to the UART you should see Welcome to Bitthunder on the console.

I added a defconfig mechanism which also configures the whole system for RPi automatically.

I'll send you my README that I think I didn't push yet.

I was about to start on a cross-platform USB stack, do you have any ideas on how to get started with that? Its quite essential to make the RPi useful I think.

Cheers, 

James

**Comment by ririw** [comment]
Awesome. Once I get the readme and work out debconfig, I'll rewrite to the post to use that, because it sounds like the better way (and maybe leave a section for doing it manually).

Unfortunately I don't know anything about how to implement USB, OS and embedded dev aren't normally things I do. I'd be happy to help though, I really want to get the ethernet working on the pi, and it hooks in to the USB bus (I think).

Cheers, Richard.

**Comment by jameswalmsley** [comment]
I added instructions to #34

**Comment by jameswalmsley** [comment]
USB is a pain, mainly because I need a good excuse to work on it, and it looks time-consuming.
Although I'm getting more and more pressure to implement stuff on bitthunder at work, so hopefully soon.
